/*  	1.START
	2. IMPORT SCANNER CLASS FROM JAVA UTIL. FOR INPUT COLLECTION	
	3. CREATE A CLASS FILE AND NAME
	4. CREATE THE MAIN METHOD
	5. COLLECT TWO INPUT FROM THE USER FOR FIRSTNUMBER AND SECOND NUMBER
    	6. DECLARE AND INITIALISE A VARIABLE FOR THE TOTAL RESULT
    	7. DISPLAY RESULT 
	8. END MAIN METHOD
	9. CREATE ANOTHER METHOD INTO MY CLASS FOR TOTAL OF TWO NUMBER
	10. RETURN THE CALCULATED VALUE OF TOTAL USING THIS FORMULA:
	 (A + B )
	11. END METHOD */


public class NumberTwo {
public static void main (String [] args){
	int totalResult = addingTen (15);

	System.out.print(totalResult);

	}
public static int addingTen ( int a ) {
int total = a + 10;
return total;
	}
	
}